// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v5/models"
)

// DeleteServerReader is a Reader for the DeleteServer structure.
type DeleteServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteServerAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteServerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteServerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteServerAccepted creates a DeleteServerAccepted with default headers values
func NewDeleteServerAccepted() *DeleteServerAccepted {
	return &DeleteServerAccepted{}
}

/*
DeleteServerAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type DeleteServerAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string
}

// IsSuccess returns true when this delete server accepted response has a 2xx status code
func (o *DeleteServerAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete server accepted response has a 3xx status code
func (o *DeleteServerAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete server accepted response has a 4xx status code
func (o *DeleteServerAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete server accepted response has a 5xx status code
func (o *DeleteServerAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete server accepted response a status code equal to that given
func (o *DeleteServerAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete server accepted response
func (o *DeleteServerAccepted) Code() int {
	return 202
}

func (o *DeleteServerAccepted) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServerAccepted ", 202)
}

func (o *DeleteServerAccepted) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServerAccepted ", 202)
}

func (o *DeleteServerAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	return nil
}

// NewDeleteServerNoContent creates a DeleteServerNoContent with default headers values
func NewDeleteServerNoContent() *DeleteServerNoContent {
	return &DeleteServerNoContent{}
}

/*
DeleteServerNoContent describes a response with status code 204, with default header values.

Server deleted
*/
type DeleteServerNoContent struct {
}

// IsSuccess returns true when this delete server no content response has a 2xx status code
func (o *DeleteServerNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete server no content response has a 3xx status code
func (o *DeleteServerNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete server no content response has a 4xx status code
func (o *DeleteServerNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete server no content response has a 5xx status code
func (o *DeleteServerNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete server no content response a status code equal to that given
func (o *DeleteServerNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete server no content response
func (o *DeleteServerNoContent) Code() int {
	return 204
}

func (o *DeleteServerNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServerNoContent ", 204)
}

func (o *DeleteServerNoContent) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServerNoContent ", 204)
}

func (o *DeleteServerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServerNotFound creates a DeleteServerNotFound with default headers values
func NewDeleteServerNotFound() *DeleteServerNotFound {
	return &DeleteServerNotFound{}
}

/*
DeleteServerNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type DeleteServerNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this delete server not found response has a 2xx status code
func (o *DeleteServerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete server not found response has a 3xx status code
func (o *DeleteServerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete server not found response has a 4xx status code
func (o *DeleteServerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete server not found response has a 5xx status code
func (o *DeleteServerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete server not found response a status code equal to that given
func (o *DeleteServerNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete server not found response
func (o *DeleteServerNotFound) Code() int {
	return 404
}

func (o *DeleteServerNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServerNotFound  %+v", 404, o.Payload)
}

func (o *DeleteServerNotFound) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServerNotFound  %+v", 404, o.Payload)
}

func (o *DeleteServerNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteServerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteServerDefault creates a DeleteServerDefault with default headers values
func NewDeleteServerDefault(code int) *DeleteServerDefault {
	return &DeleteServerDefault{
		_statusCode: code,
	}
}

/*
DeleteServerDefault describes a response with status code -1, with default header values.

General Error
*/
type DeleteServerDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this delete server default response has a 2xx status code
func (o *DeleteServerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete server default response has a 3xx status code
func (o *DeleteServerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete server default response has a 4xx status code
func (o *DeleteServerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete server default response has a 5xx status code
func (o *DeleteServerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete server default response a status code equal to that given
func (o *DeleteServerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete server default response
func (o *DeleteServerDefault) Code() int {
	return o._statusCode
}

func (o *DeleteServerDefault) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServer default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteServerDefault) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/servers/{name}][%d] deleteServer default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteServerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
