// Code generated by go-swagger; DO NOT EDIT.

package f_c_g_i_app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/haproxytech/client-native/v4/models"
)

// GetFCGIAppReader is a Reader for the GetFCGIApp structure.
type GetFCGIAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFCGIAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFCGIAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetFCGIAppNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetFCGIAppDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetFCGIAppOK creates a GetFCGIAppOK with default headers values
func NewGetFCGIAppOK() *GetFCGIAppOK {
	return &GetFCGIAppOK{}
}

/*
GetFCGIAppOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetFCGIAppOK struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *GetFCGIAppOKBody
}

// IsSuccess returns true when this get f c g i app o k response has a 2xx status code
func (o *GetFCGIAppOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get f c g i app o k response has a 3xx status code
func (o *GetFCGIAppOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get f c g i app o k response has a 4xx status code
func (o *GetFCGIAppOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get f c g i app o k response has a 5xx status code
func (o *GetFCGIAppOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get f c g i app o k response a status code equal to that given
func (o *GetFCGIAppOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetFCGIAppOK) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/fcgi_apps/{name}][%d] getFCGIAppOK  %+v", 200, o.Payload)
}

func (o *GetFCGIAppOK) String() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/fcgi_apps/{name}][%d] getFCGIAppOK  %+v", 200, o.Payload)
}

func (o *GetFCGIAppOK) GetPayload() *GetFCGIAppOKBody {
	return o.Payload
}

func (o *GetFCGIAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(GetFCGIAppOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFCGIAppNotFound creates a GetFCGIAppNotFound with default headers values
func NewGetFCGIAppNotFound() *GetFCGIAppNotFound {
	return &GetFCGIAppNotFound{}
}

/*
GetFCGIAppNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type GetFCGIAppNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get f c g i app not found response has a 2xx status code
func (o *GetFCGIAppNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get f c g i app not found response has a 3xx status code
func (o *GetFCGIAppNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get f c g i app not found response has a 4xx status code
func (o *GetFCGIAppNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get f c g i app not found response has a 5xx status code
func (o *GetFCGIAppNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get f c g i app not found response a status code equal to that given
func (o *GetFCGIAppNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetFCGIAppNotFound) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/fcgi_apps/{name}][%d] getFCGIAppNotFound  %+v", 404, o.Payload)
}

func (o *GetFCGIAppNotFound) String() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/fcgi_apps/{name}][%d] getFCGIAppNotFound  %+v", 404, o.Payload)
}

func (o *GetFCGIAppNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetFCGIAppNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFCGIAppDefault creates a GetFCGIAppDefault with default headers values
func NewGetFCGIAppDefault(code int) *GetFCGIAppDefault {
	return &GetFCGIAppDefault{
		_statusCode: code,
	}
}

/*
GetFCGIAppDefault describes a response with status code -1, with default header values.

General Error
*/
type GetFCGIAppDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the get f c g i app default response
func (o *GetFCGIAppDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get f c g i app default response has a 2xx status code
func (o *GetFCGIAppDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get f c g i app default response has a 3xx status code
func (o *GetFCGIAppDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get f c g i app default response has a 4xx status code
func (o *GetFCGIAppDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get f c g i app default response has a 5xx status code
func (o *GetFCGIAppDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get f c g i app default response a status code equal to that given
func (o *GetFCGIAppDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetFCGIAppDefault) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/fcgi_apps/{name}][%d] getFCGIApp default  %+v", o._statusCode, o.Payload)
}

func (o *GetFCGIAppDefault) String() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/fcgi_apps/{name}][%d] getFCGIApp default  %+v", o._statusCode, o.Payload)
}

func (o *GetFCGIAppDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetFCGIAppDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetFCGIAppOKBody get f c g i app o k body
swagger:model GetFCGIAppOKBody
*/
type GetFCGIAppOKBody struct {

	// version
	Version int64 `json:"_version,omitempty"`

	// data
	Data *models.FcgiApp `json:"data,omitempty"`
}

// Validate validates this get f c g i app o k body
func (o *GetFCGIAppOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFCGIAppOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getFCGIAppOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getFCGIAppOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get f c g i app o k body based on the context it is used
func (o *GetFCGIAppOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFCGIAppOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getFCGIAppOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getFCGIAppOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetFCGIAppOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFCGIAppOKBody) UnmarshalBinary(b []byte) error {
	var res GetFCGIAppOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
