// Code generated by go-swagger; DO NOT EDIT.

package http_error_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/haproxytech/client-native/v5/models"
)

// NewCreateHTTPErrorRuleParams creates a new CreateHTTPErrorRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateHTTPErrorRuleParams() *CreateHTTPErrorRuleParams {
	return &CreateHTTPErrorRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateHTTPErrorRuleParamsWithTimeout creates a new CreateHTTPErrorRuleParams object
// with the ability to set a timeout on a request.
func NewCreateHTTPErrorRuleParamsWithTimeout(timeout time.Duration) *CreateHTTPErrorRuleParams {
	return &CreateHTTPErrorRuleParams{
		timeout: timeout,
	}
}

// NewCreateHTTPErrorRuleParamsWithContext creates a new CreateHTTPErrorRuleParams object
// with the ability to set a context for a request.
func NewCreateHTTPErrorRuleParamsWithContext(ctx context.Context) *CreateHTTPErrorRuleParams {
	return &CreateHTTPErrorRuleParams{
		Context: ctx,
	}
}

// NewCreateHTTPErrorRuleParamsWithHTTPClient creates a new CreateHTTPErrorRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateHTTPErrorRuleParamsWithHTTPClient(client *http.Client) *CreateHTTPErrorRuleParams {
	return &CreateHTTPErrorRuleParams{
		HTTPClient: client,
	}
}

/*
CreateHTTPErrorRuleParams contains all the parameters to send to the API endpoint

	for the create HTTP error rule operation.

	Typically these are written to a http.Request.
*/
type CreateHTTPErrorRuleParams struct {

	// Data.
	Data *models.HTTPErrorRule

	/* ForceReload.

	   If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	*/
	ForceReload *bool

	/* ParentName.

	   Parent name
	*/
	ParentName *string

	/* ParentType.

	   Parent type
	*/
	ParentType string

	/* TransactionID.

	   ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	*/
	TransactionID *string

	/* Version.

	   Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.
	*/
	Version *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create HTTP error rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateHTTPErrorRuleParams) WithDefaults() *CreateHTTPErrorRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create HTTP error rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateHTTPErrorRuleParams) SetDefaults() {
	var (
		forceReloadDefault = bool(false)
	)

	val := CreateHTTPErrorRuleParams{
		ForceReload: &forceReloadDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithTimeout(timeout time.Duration) *CreateHTTPErrorRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithContext(ctx context.Context) *CreateHTTPErrorRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithHTTPClient(client *http.Client) *CreateHTTPErrorRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithData(data *models.HTTPErrorRule) *CreateHTTPErrorRuleParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetData(data *models.HTTPErrorRule) {
	o.Data = data
}

// WithForceReload adds the forceReload to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithForceReload(forceReload *bool) *CreateHTTPErrorRuleParams {
	o.SetForceReload(forceReload)
	return o
}

// SetForceReload adds the forceReload to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetForceReload(forceReload *bool) {
	o.ForceReload = forceReload
}

// WithParentName adds the parentName to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithParentName(parentName *string) *CreateHTTPErrorRuleParams {
	o.SetParentName(parentName)
	return o
}

// SetParentName adds the parentName to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetParentName(parentName *string) {
	o.ParentName = parentName
}

// WithParentType adds the parentType to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithParentType(parentType string) *CreateHTTPErrorRuleParams {
	o.SetParentType(parentType)
	return o
}

// SetParentType adds the parentType to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetParentType(parentType string) {
	o.ParentType = parentType
}

// WithTransactionID adds the transactionID to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithTransactionID(transactionID *string) *CreateHTTPErrorRuleParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WithVersion adds the version to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) WithVersion(version *int64) *CreateHTTPErrorRuleParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the create HTTP error rule params
func (o *CreateHTTPErrorRuleParams) SetVersion(version *int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *CreateHTTPErrorRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if o.ForceReload != nil {

		// query param force_reload
		var qrForceReload bool

		if o.ForceReload != nil {
			qrForceReload = *o.ForceReload
		}
		qForceReload := swag.FormatBool(qrForceReload)
		if qForceReload != "" {

			if err := r.SetQueryParam("force_reload", qForceReload); err != nil {
				return err
			}
		}
	}

	if o.ParentName != nil {

		// query param parent_name
		var qrParentName string

		if o.ParentName != nil {
			qrParentName = *o.ParentName
		}
		qParentName := qrParentName
		if qParentName != "" {

			if err := r.SetQueryParam("parent_name", qParentName); err != nil {
				return err
			}
		}
	}

	// query param parent_type
	qrParentType := o.ParentType
	qParentType := qrParentType
	if qParentType != "" {

		if err := r.SetQueryParam("parent_type", qParentType); err != nil {
			return err
		}
	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string

		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {

			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}
	}

	if o.Version != nil {

		// query param version
		var qrVersion int64

		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := swag.FormatInt64(qrVersion)
		if qVersion != "" {

			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
