// Code generated by go-swagger; DO NOT EDIT.

package http_errors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHTTPErrorsSectionParams creates a new GetHTTPErrorsSectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHTTPErrorsSectionParams() *GetHTTPErrorsSectionParams {
	return &GetHTTPErrorsSectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHTTPErrorsSectionParamsWithTimeout creates a new GetHTTPErrorsSectionParams object
// with the ability to set a timeout on a request.
func NewGetHTTPErrorsSectionParamsWithTimeout(timeout time.Duration) *GetHTTPErrorsSectionParams {
	return &GetHTTPErrorsSectionParams{
		timeout: timeout,
	}
}

// NewGetHTTPErrorsSectionParamsWithContext creates a new GetHTTPErrorsSectionParams object
// with the ability to set a context for a request.
func NewGetHTTPErrorsSectionParamsWithContext(ctx context.Context) *GetHTTPErrorsSectionParams {
	return &GetHTTPErrorsSectionParams{
		Context: ctx,
	}
}

// NewGetHTTPErrorsSectionParamsWithHTTPClient creates a new GetHTTPErrorsSectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHTTPErrorsSectionParamsWithHTTPClient(client *http.Client) *GetHTTPErrorsSectionParams {
	return &GetHTTPErrorsSectionParams{
		HTTPClient: client,
	}
}

/*
GetHTTPErrorsSectionParams contains all the parameters to send to the API endpoint

	for the get HTTP errors section operation.

	Typically these are written to a http.Request.
*/
type GetHTTPErrorsSectionParams struct {

	/* Name.

	   http-error section name
	*/
	Name string

	/* TransactionID.

	   ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	*/
	TransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get HTTP errors section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHTTPErrorsSectionParams) WithDefaults() *GetHTTPErrorsSectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get HTTP errors section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHTTPErrorsSectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) WithTimeout(timeout time.Duration) *GetHTTPErrorsSectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) WithContext(ctx context.Context) *GetHTTPErrorsSectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) WithHTTPClient(client *http.Client) *GetHTTPErrorsSectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) WithName(name string) *GetHTTPErrorsSectionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) SetName(name string) {
	o.Name = name
}

// WithTransactionID adds the transactionID to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) WithTransactionID(transactionID *string) *GetHTTPErrorsSectionParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get HTTP errors section params
func (o *GetHTTPErrorsSectionParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetHTTPErrorsSectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string

		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {

			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
