// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v4/models"
)

// CreateSiteReader is a Reader for the CreateSite structure.
type CreateSiteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSiteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateSiteCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewCreateSiteAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSiteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateSiteConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateSiteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSiteCreated creates a CreateSiteCreated with default headers values
func NewCreateSiteCreated() *CreateSiteCreated {
	return &CreateSiteCreated{}
}

/*
CreateSiteCreated describes a response with status code 201, with default header values.

Site created
*/
type CreateSiteCreated struct {
	Payload *models.Site
}

// IsSuccess returns true when this create site created response has a 2xx status code
func (o *CreateSiteCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create site created response has a 3xx status code
func (o *CreateSiteCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create site created response has a 4xx status code
func (o *CreateSiteCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create site created response has a 5xx status code
func (o *CreateSiteCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create site created response a status code equal to that given
func (o *CreateSiteCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateSiteCreated) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteCreated  %+v", 201, o.Payload)
}

func (o *CreateSiteCreated) String() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteCreated  %+v", 201, o.Payload)
}

func (o *CreateSiteCreated) GetPayload() *models.Site {
	return o.Payload
}

func (o *CreateSiteCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Site)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSiteAccepted creates a CreateSiteAccepted with default headers values
func NewCreateSiteAccepted() *CreateSiteAccepted {
	return &CreateSiteAccepted{}
}

/*
CreateSiteAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type CreateSiteAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string

	Payload *models.Site
}

// IsSuccess returns true when this create site accepted response has a 2xx status code
func (o *CreateSiteAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create site accepted response has a 3xx status code
func (o *CreateSiteAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create site accepted response has a 4xx status code
func (o *CreateSiteAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this create site accepted response has a 5xx status code
func (o *CreateSiteAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this create site accepted response a status code equal to that given
func (o *CreateSiteAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *CreateSiteAccepted) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteAccepted  %+v", 202, o.Payload)
}

func (o *CreateSiteAccepted) String() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteAccepted  %+v", 202, o.Payload)
}

func (o *CreateSiteAccepted) GetPayload() *models.Site {
	return o.Payload
}

func (o *CreateSiteAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	o.Payload = new(models.Site)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSiteBadRequest creates a CreateSiteBadRequest with default headers values
func NewCreateSiteBadRequest() *CreateSiteBadRequest {
	return &CreateSiteBadRequest{}
}

/*
CreateSiteBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateSiteBadRequest struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this create site bad request response has a 2xx status code
func (o *CreateSiteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create site bad request response has a 3xx status code
func (o *CreateSiteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create site bad request response has a 4xx status code
func (o *CreateSiteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create site bad request response has a 5xx status code
func (o *CreateSiteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create site bad request response a status code equal to that given
func (o *CreateSiteBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateSiteBadRequest) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteBadRequest  %+v", 400, o.Payload)
}

func (o *CreateSiteBadRequest) String() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteBadRequest  %+v", 400, o.Payload)
}

func (o *CreateSiteBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateSiteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSiteConflict creates a CreateSiteConflict with default headers values
func NewCreateSiteConflict() *CreateSiteConflict {
	return &CreateSiteConflict{}
}

/*
CreateSiteConflict describes a response with status code 409, with default header values.

The specified resource already exists
*/
type CreateSiteConflict struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this create site conflict response has a 2xx status code
func (o *CreateSiteConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create site conflict response has a 3xx status code
func (o *CreateSiteConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create site conflict response has a 4xx status code
func (o *CreateSiteConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create site conflict response has a 5xx status code
func (o *CreateSiteConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create site conflict response a status code equal to that given
func (o *CreateSiteConflict) IsCode(code int) bool {
	return code == 409
}

func (o *CreateSiteConflict) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteConflict  %+v", 409, o.Payload)
}

func (o *CreateSiteConflict) String() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSiteConflict  %+v", 409, o.Payload)
}

func (o *CreateSiteConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateSiteConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSiteDefault creates a CreateSiteDefault with default headers values
func NewCreateSiteDefault(code int) *CreateSiteDefault {
	return &CreateSiteDefault{
		_statusCode: code,
	}
}

/*
CreateSiteDefault describes a response with status code -1, with default header values.

General Error
*/
type CreateSiteDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the create site default response
func (o *CreateSiteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this create site default response has a 2xx status code
func (o *CreateSiteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create site default response has a 3xx status code
func (o *CreateSiteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create site default response has a 4xx status code
func (o *CreateSiteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create site default response has a 5xx status code
func (o *CreateSiteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create site default response a status code equal to that given
func (o *CreateSiteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *CreateSiteDefault) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSite default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSiteDefault) String() string {
	return fmt.Sprintf("[POST /services/haproxy/sites][%d] createSite default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSiteDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateSiteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
