// Code generated by go-swagger; DO NOT EDIT.

package tcp_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/haproxytech/client-native/v3/models"
)

// GetTCPChecksReader is a Reader for the GetTCPChecks structure.
type GetTCPChecksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTCPChecksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTCPChecksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetTCPChecksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTCPChecksOK creates a GetTCPChecksOK with default headers values
func NewGetTCPChecksOK() *GetTCPChecksOK {
	return &GetTCPChecksOK{}
}

/*GetTCPChecksOK handles this case with default header values.

Successful operation
*/
type GetTCPChecksOK struct {
	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *GetTCPChecksOKBody
}

func (o *GetTCPChecksOK) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tcp_checks][%d] getTcpChecksOK  %+v", 200, o.Payload)
}

func (o *GetTCPChecksOK) GetPayload() *GetTCPChecksOKBody {
	return o.Payload
}

func (o *GetTCPChecksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(GetTCPChecksOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTCPChecksDefault creates a GetTCPChecksDefault with default headers values
func NewGetTCPChecksDefault(code int) *GetTCPChecksDefault {
	return &GetTCPChecksDefault{
		_statusCode: code,
	}
}

/*GetTCPChecksDefault handles this case with default header values.

General Error
*/
type GetTCPChecksDefault struct {
	_statusCode int

	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the get TCP checks default response
func (o *GetTCPChecksDefault) Code() int {
	return o._statusCode
}

func (o *GetTCPChecksDefault) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tcp_checks][%d] getTCPChecks default  %+v", o._statusCode, o.Payload)
}

func (o *GetTCPChecksDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTCPChecksDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTCPChecksOKBody get TCP checks o k body
swagger:model GetTCPChecksOKBody
*/
type GetTCPChecksOKBody struct {

	// version
	Version int64 `json:"_version,omitempty"`

	// data
	// Required: true
	Data models.TCPChecks `json:"data"`
}

// Validate validates this get TCP checks o k body
func (o *GetTCPChecksOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTCPChecksOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getTcpChecksOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if err := o.Data.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getTcpChecksOK" + "." + "data")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTCPChecksOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTCPChecksOKBody) UnmarshalBinary(b []byte) error {
	var res GetTCPChecksOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
