// Code generated by go-swagger; DO NOT EDIT.

package process_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProgramsParams creates a new GetProgramsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProgramsParams() *GetProgramsParams {
	return &GetProgramsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProgramsParamsWithTimeout creates a new GetProgramsParams object
// with the ability to set a timeout on a request.
func NewGetProgramsParamsWithTimeout(timeout time.Duration) *GetProgramsParams {
	return &GetProgramsParams{
		timeout: timeout,
	}
}

// NewGetProgramsParamsWithContext creates a new GetProgramsParams object
// with the ability to set a context for a request.
func NewGetProgramsParamsWithContext(ctx context.Context) *GetProgramsParams {
	return &GetProgramsParams{
		Context: ctx,
	}
}

// NewGetProgramsParamsWithHTTPClient creates a new GetProgramsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProgramsParamsWithHTTPClient(client *http.Client) *GetProgramsParams {
	return &GetProgramsParams{
		HTTPClient: client,
	}
}

/*
GetProgramsParams contains all the parameters to send to the API endpoint

	for the get programs operation.

	Typically these are written to a http.Request.
*/
type GetProgramsParams struct {

	/* TransactionID.

	   ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	*/
	TransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get programs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProgramsParams) WithDefaults() *GetProgramsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get programs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProgramsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get programs params
func (o *GetProgramsParams) WithTimeout(timeout time.Duration) *GetProgramsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get programs params
func (o *GetProgramsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get programs params
func (o *GetProgramsParams) WithContext(ctx context.Context) *GetProgramsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get programs params
func (o *GetProgramsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get programs params
func (o *GetProgramsParams) WithHTTPClient(client *http.Client) *GetProgramsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get programs params
func (o *GetProgramsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTransactionID adds the transactionID to the get programs params
func (o *GetProgramsParams) WithTransactionID(transactionID *string) *GetProgramsParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get programs params
func (o *GetProgramsParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProgramsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string

		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {

			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
