// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTablesParams creates a new GetTablesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTablesParams() *GetTablesParams {
	return &GetTablesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTablesParamsWithTimeout creates a new GetTablesParams object
// with the ability to set a timeout on a request.
func NewGetTablesParamsWithTimeout(timeout time.Duration) *GetTablesParams {
	return &GetTablesParams{
		timeout: timeout,
	}
}

// NewGetTablesParamsWithContext creates a new GetTablesParams object
// with the ability to set a context for a request.
func NewGetTablesParamsWithContext(ctx context.Context) *GetTablesParams {
	return &GetTablesParams{
		Context: ctx,
	}
}

// NewGetTablesParamsWithHTTPClient creates a new GetTablesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTablesParamsWithHTTPClient(client *http.Client) *GetTablesParams {
	return &GetTablesParams{
		HTTPClient: client,
	}
}

/*
GetTablesParams contains all the parameters to send to the API endpoint

	for the get tables operation.

	Typically these are written to a http.Request.
*/
type GetTablesParams struct {

	/* PeerSection.

	   Parent peer section name
	*/
	PeerSection string

	/* TransactionID.

	   ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	*/
	TransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tables params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTablesParams) WithDefaults() *GetTablesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tables params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTablesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tables params
func (o *GetTablesParams) WithTimeout(timeout time.Duration) *GetTablesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tables params
func (o *GetTablesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tables params
func (o *GetTablesParams) WithContext(ctx context.Context) *GetTablesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tables params
func (o *GetTablesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tables params
func (o *GetTablesParams) WithHTTPClient(client *http.Client) *GetTablesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tables params
func (o *GetTablesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPeerSection adds the peerSection to the get tables params
func (o *GetTablesParams) WithPeerSection(peerSection string) *GetTablesParams {
	o.SetPeerSection(peerSection)
	return o
}

// SetPeerSection adds the peerSection to the get tables params
func (o *GetTablesParams) SetPeerSection(peerSection string) {
	o.PeerSection = peerSection
}

// WithTransactionID adds the transactionID to the get tables params
func (o *GetTablesParams) WithTransactionID(transactionID *string) *GetTablesParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get tables params
func (o *GetTablesParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTablesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param peer_section
	qrPeerSection := o.PeerSection
	qPeerSection := qrPeerSection
	if qPeerSection != "" {

		if err := r.SetQueryParam("peer_section", qPeerSection); err != nil {
			return err
		}
	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string

		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {

			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
