// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/haproxytech/client-native/v5/models"
)

// GetTableReader is a Reader for the GetTable structure.
type GetTableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTableNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetTableDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTableOK creates a GetTableOK with default headers values
func NewGetTableOK() *GetTableOK {
	return &GetTableOK{}
}

/*
GetTableOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetTableOK struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *GetTableOKBody
}

// IsSuccess returns true when this get table o k response has a 2xx status code
func (o *GetTableOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get table o k response has a 3xx status code
func (o *GetTableOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get table o k response has a 4xx status code
func (o *GetTableOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get table o k response has a 5xx status code
func (o *GetTableOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get table o k response a status code equal to that given
func (o *GetTableOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get table o k response
func (o *GetTableOK) Code() int {
	return 200
}

func (o *GetTableOK) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tables/{name}][%d] getTableOK  %+v", 200, o.Payload)
}

func (o *GetTableOK) String() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tables/{name}][%d] getTableOK  %+v", 200, o.Payload)
}

func (o *GetTableOK) GetPayload() *GetTableOKBody {
	return o.Payload
}

func (o *GetTableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(GetTableOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTableNotFound creates a GetTableNotFound with default headers values
func NewGetTableNotFound() *GetTableNotFound {
	return &GetTableNotFound{}
}

/*
GetTableNotFound describes a response with status code 404, with default header values.

The specified resource already exists
*/
type GetTableNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get table not found response has a 2xx status code
func (o *GetTableNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get table not found response has a 3xx status code
func (o *GetTableNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get table not found response has a 4xx status code
func (o *GetTableNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get table not found response has a 5xx status code
func (o *GetTableNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get table not found response a status code equal to that given
func (o *GetTableNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get table not found response
func (o *GetTableNotFound) Code() int {
	return 404
}

func (o *GetTableNotFound) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tables/{name}][%d] getTableNotFound  %+v", 404, o.Payload)
}

func (o *GetTableNotFound) String() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tables/{name}][%d] getTableNotFound  %+v", 404, o.Payload)
}

func (o *GetTableNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTableNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTableDefault creates a GetTableDefault with default headers values
func NewGetTableDefault(code int) *GetTableDefault {
	return &GetTableDefault{
		_statusCode: code,
	}
}

/*
GetTableDefault describes a response with status code -1, with default header values.

General Error
*/
type GetTableDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get table default response has a 2xx status code
func (o *GetTableDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get table default response has a 3xx status code
func (o *GetTableDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get table default response has a 4xx status code
func (o *GetTableDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get table default response has a 5xx status code
func (o *GetTableDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get table default response a status code equal to that given
func (o *GetTableDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get table default response
func (o *GetTableDefault) Code() int {
	return o._statusCode
}

func (o *GetTableDefault) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tables/{name}][%d] getTable default  %+v", o._statusCode, o.Payload)
}

func (o *GetTableDefault) String() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tables/{name}][%d] getTable default  %+v", o._statusCode, o.Payload)
}

func (o *GetTableDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTableDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetTableOKBody get table o k body
swagger:model GetTableOKBody
*/
type GetTableOKBody struct {

	// version
	Version int64 `json:"_version,omitempty"`

	// data
	Data *models.Table `json:"data,omitempty"`
}

// Validate validates this get table o k body
func (o *GetTableOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTableOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getTableOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getTableOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get table o k body based on the context it is used
func (o *GetTableOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTableOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getTableOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getTableOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTableOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTableOKBody) UnmarshalBinary(b []byte) error {
	var res GetTableOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
