// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/haproxytech/client-native/v5/models"
)

// NewReplaceTableParams creates a new ReplaceTableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReplaceTableParams() *ReplaceTableParams {
	return &ReplaceTableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceTableParamsWithTimeout creates a new ReplaceTableParams object
// with the ability to set a timeout on a request.
func NewReplaceTableParamsWithTimeout(timeout time.Duration) *ReplaceTableParams {
	return &ReplaceTableParams{
		timeout: timeout,
	}
}

// NewReplaceTableParamsWithContext creates a new ReplaceTableParams object
// with the ability to set a context for a request.
func NewReplaceTableParamsWithContext(ctx context.Context) *ReplaceTableParams {
	return &ReplaceTableParams{
		Context: ctx,
	}
}

// NewReplaceTableParamsWithHTTPClient creates a new ReplaceTableParams object
// with the ability to set a custom HTTPClient for a request.
func NewReplaceTableParamsWithHTTPClient(client *http.Client) *ReplaceTableParams {
	return &ReplaceTableParams{
		HTTPClient: client,
	}
}

/*
ReplaceTableParams contains all the parameters to send to the API endpoint

	for the replace table operation.

	Typically these are written to a http.Request.
*/
type ReplaceTableParams struct {

	// Data.
	Data *models.Table

	/* ForceReload.

	   If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	*/
	ForceReload *bool

	/* Name.

	   Table name
	*/
	Name string

	/* PeerSection.

	   Parent peers name
	*/
	PeerSection string

	/* TransactionID.

	   ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	*/
	TransactionID *string

	/* Version.

	   Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.
	*/
	Version *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the replace table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceTableParams) WithDefaults() *ReplaceTableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the replace table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceTableParams) SetDefaults() {
	var (
		forceReloadDefault = bool(false)
	)

	val := ReplaceTableParams{
		ForceReload: &forceReloadDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the replace table params
func (o *ReplaceTableParams) WithTimeout(timeout time.Duration) *ReplaceTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace table params
func (o *ReplaceTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace table params
func (o *ReplaceTableParams) WithContext(ctx context.Context) *ReplaceTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace table params
func (o *ReplaceTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace table params
func (o *ReplaceTableParams) WithHTTPClient(client *http.Client) *ReplaceTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace table params
func (o *ReplaceTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the replace table params
func (o *ReplaceTableParams) WithData(data *models.Table) *ReplaceTableParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the replace table params
func (o *ReplaceTableParams) SetData(data *models.Table) {
	o.Data = data
}

// WithForceReload adds the forceReload to the replace table params
func (o *ReplaceTableParams) WithForceReload(forceReload *bool) *ReplaceTableParams {
	o.SetForceReload(forceReload)
	return o
}

// SetForceReload adds the forceReload to the replace table params
func (o *ReplaceTableParams) SetForceReload(forceReload *bool) {
	o.ForceReload = forceReload
}

// WithName adds the name to the replace table params
func (o *ReplaceTableParams) WithName(name string) *ReplaceTableParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the replace table params
func (o *ReplaceTableParams) SetName(name string) {
	o.Name = name
}

// WithPeerSection adds the peerSection to the replace table params
func (o *ReplaceTableParams) WithPeerSection(peerSection string) *ReplaceTableParams {
	o.SetPeerSection(peerSection)
	return o
}

// SetPeerSection adds the peerSection to the replace table params
func (o *ReplaceTableParams) SetPeerSection(peerSection string) {
	o.PeerSection = peerSection
}

// WithTransactionID adds the transactionID to the replace table params
func (o *ReplaceTableParams) WithTransactionID(transactionID *string) *ReplaceTableParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the replace table params
func (o *ReplaceTableParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WithVersion adds the version to the replace table params
func (o *ReplaceTableParams) WithVersion(version *int64) *ReplaceTableParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the replace table params
func (o *ReplaceTableParams) SetVersion(version *int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if o.ForceReload != nil {

		// query param force_reload
		var qrForceReload bool

		if o.ForceReload != nil {
			qrForceReload = *o.ForceReload
		}
		qForceReload := swag.FormatBool(qrForceReload)
		if qForceReload != "" {

			if err := r.SetQueryParam("force_reload", qForceReload); err != nil {
				return err
			}
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// query param peer_section
	qrPeerSection := o.PeerSection
	qPeerSection := qrPeerSection
	if qPeerSection != "" {

		if err := r.SetQueryParam("peer_section", qPeerSection); err != nil {
			return err
		}
	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string

		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {

			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}
	}

	if o.Version != nil {

		// query param version
		var qrVersion int64

		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := swag.FormatInt64(qrVersion)
		if qVersion != "" {

			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
