// Code generated by go-swagger; DO NOT EDIT.

package ring

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v4/models"
)

// DeleteRingReader is a Reader for the DeleteRing structure.
type DeleteRingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteRingAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteRingNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteRingNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteRingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteRingAccepted creates a DeleteRingAccepted with default headers values
func NewDeleteRingAccepted() *DeleteRingAccepted {
	return &DeleteRingAccepted{}
}

/*
DeleteRingAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type DeleteRingAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string
}

// IsSuccess returns true when this delete ring accepted response has a 2xx status code
func (o *DeleteRingAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete ring accepted response has a 3xx status code
func (o *DeleteRingAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete ring accepted response has a 4xx status code
func (o *DeleteRingAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete ring accepted response has a 5xx status code
func (o *DeleteRingAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete ring accepted response a status code equal to that given
func (o *DeleteRingAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *DeleteRingAccepted) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRingAccepted ", 202)
}

func (o *DeleteRingAccepted) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRingAccepted ", 202)
}

func (o *DeleteRingAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	return nil
}

// NewDeleteRingNoContent creates a DeleteRingNoContent with default headers values
func NewDeleteRingNoContent() *DeleteRingNoContent {
	return &DeleteRingNoContent{}
}

/*
DeleteRingNoContent describes a response with status code 204, with default header values.

Ring deleted
*/
type DeleteRingNoContent struct {
}

// IsSuccess returns true when this delete ring no content response has a 2xx status code
func (o *DeleteRingNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete ring no content response has a 3xx status code
func (o *DeleteRingNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete ring no content response has a 4xx status code
func (o *DeleteRingNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete ring no content response has a 5xx status code
func (o *DeleteRingNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete ring no content response a status code equal to that given
func (o *DeleteRingNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteRingNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRingNoContent ", 204)
}

func (o *DeleteRingNoContent) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRingNoContent ", 204)
}

func (o *DeleteRingNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRingNotFound creates a DeleteRingNotFound with default headers values
func NewDeleteRingNotFound() *DeleteRingNotFound {
	return &DeleteRingNotFound{}
}

/*
DeleteRingNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type DeleteRingNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this delete ring not found response has a 2xx status code
func (o *DeleteRingNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete ring not found response has a 3xx status code
func (o *DeleteRingNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete ring not found response has a 4xx status code
func (o *DeleteRingNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete ring not found response has a 5xx status code
func (o *DeleteRingNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete ring not found response a status code equal to that given
func (o *DeleteRingNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteRingNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRingNotFound  %+v", 404, o.Payload)
}

func (o *DeleteRingNotFound) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRingNotFound  %+v", 404, o.Payload)
}

func (o *DeleteRingNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRingNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRingDefault creates a DeleteRingDefault with default headers values
func NewDeleteRingDefault(code int) *DeleteRingDefault {
	return &DeleteRingDefault{
		_statusCode: code,
	}
}

/*
DeleteRingDefault describes a response with status code -1, with default header values.

General Error
*/
type DeleteRingDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the delete ring default response
func (o *DeleteRingDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete ring default response has a 2xx status code
func (o *DeleteRingDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete ring default response has a 3xx status code
func (o *DeleteRingDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete ring default response has a 4xx status code
func (o *DeleteRingDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete ring default response has a 5xx status code
func (o *DeleteRingDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete ring default response a status code equal to that given
func (o *DeleteRingDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteRingDefault) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRing default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteRingDefault) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/rings/{name}][%d] deleteRing default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteRingDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
