// Code generated by go-swagger; DO NOT EDIT.

package acl_runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v5/models"
)

// GetServicesHaproxyRuntimeACLFileEntriesReader is a Reader for the GetServicesHaproxyRuntimeACLFileEntries structure.
type GetServicesHaproxyRuntimeACLFileEntriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServicesHaproxyRuntimeACLFileEntriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServicesHaproxyRuntimeACLFileEntriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetServicesHaproxyRuntimeACLFileEntriesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetServicesHaproxyRuntimeACLFileEntriesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetServicesHaproxyRuntimeACLFileEntriesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetServicesHaproxyRuntimeACLFileEntriesOK creates a GetServicesHaproxyRuntimeACLFileEntriesOK with default headers values
func NewGetServicesHaproxyRuntimeACLFileEntriesOK() *GetServicesHaproxyRuntimeACLFileEntriesOK {
	return &GetServicesHaproxyRuntimeACLFileEntriesOK{}
}

/*
GetServicesHaproxyRuntimeACLFileEntriesOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetServicesHaproxyRuntimeACLFileEntriesOK struct {
	Payload models.ACLFilesEntries
}

// IsSuccess returns true when this get services haproxy runtime Acl file entries o k response has a 2xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get services haproxy runtime Acl file entries o k response has a 3xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get services haproxy runtime Acl file entries o k response has a 4xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get services haproxy runtime Acl file entries o k response has a 5xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get services haproxy runtime Acl file entries o k response a status code equal to that given
func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get services haproxy runtime Acl file entries o k response
func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) Code() int {
	return 200
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] getServicesHaproxyRuntimeAclFileEntriesOK  %+v", 200, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) String() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] getServicesHaproxyRuntimeAclFileEntriesOK  %+v", 200, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) GetPayload() models.ACLFilesEntries {
	return o.Payload
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicesHaproxyRuntimeACLFileEntriesBadRequest creates a GetServicesHaproxyRuntimeACLFileEntriesBadRequest with default headers values
func NewGetServicesHaproxyRuntimeACLFileEntriesBadRequest() *GetServicesHaproxyRuntimeACLFileEntriesBadRequest {
	return &GetServicesHaproxyRuntimeACLFileEntriesBadRequest{}
}

/*
GetServicesHaproxyRuntimeACLFileEntriesBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetServicesHaproxyRuntimeACLFileEntriesBadRequest struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get services haproxy runtime Acl file entries bad request response has a 2xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get services haproxy runtime Acl file entries bad request response has a 3xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get services haproxy runtime Acl file entries bad request response has a 4xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get services haproxy runtime Acl file entries bad request response has a 5xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get services haproxy runtime Acl file entries bad request response a status code equal to that given
func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get services haproxy runtime Acl file entries bad request response
func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) Code() int {
	return 400
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] getServicesHaproxyRuntimeAclFileEntriesBadRequest  %+v", 400, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) String() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] getServicesHaproxyRuntimeAclFileEntriesBadRequest  %+v", 400, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicesHaproxyRuntimeACLFileEntriesNotFound creates a GetServicesHaproxyRuntimeACLFileEntriesNotFound with default headers values
func NewGetServicesHaproxyRuntimeACLFileEntriesNotFound() *GetServicesHaproxyRuntimeACLFileEntriesNotFound {
	return &GetServicesHaproxyRuntimeACLFileEntriesNotFound{}
}

/*
GetServicesHaproxyRuntimeACLFileEntriesNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type GetServicesHaproxyRuntimeACLFileEntriesNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get services haproxy runtime Acl file entries not found response has a 2xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get services haproxy runtime Acl file entries not found response has a 3xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get services haproxy runtime Acl file entries not found response has a 4xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get services haproxy runtime Acl file entries not found response has a 5xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get services haproxy runtime Acl file entries not found response a status code equal to that given
func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get services haproxy runtime Acl file entries not found response
func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) Code() int {
	return 404
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] getServicesHaproxyRuntimeAclFileEntriesNotFound  %+v", 404, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) String() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] getServicesHaproxyRuntimeAclFileEntriesNotFound  %+v", 404, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicesHaproxyRuntimeACLFileEntriesDefault creates a GetServicesHaproxyRuntimeACLFileEntriesDefault with default headers values
func NewGetServicesHaproxyRuntimeACLFileEntriesDefault(code int) *GetServicesHaproxyRuntimeACLFileEntriesDefault {
	return &GetServicesHaproxyRuntimeACLFileEntriesDefault{
		_statusCode: code,
	}
}

/*
GetServicesHaproxyRuntimeACLFileEntriesDefault describes a response with status code -1, with default header values.

General Error
*/
type GetServicesHaproxyRuntimeACLFileEntriesDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get services haproxy runtime ACL file entries default response has a 2xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get services haproxy runtime ACL file entries default response has a 3xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get services haproxy runtime ACL file entries default response has a 4xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get services haproxy runtime ACL file entries default response has a 5xx status code
func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get services haproxy runtime ACL file entries default response a status code equal to that given
func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get services haproxy runtime ACL file entries default response
func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) Code() int {
	return o._statusCode
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] GetServicesHaproxyRuntimeACLFileEntries default  %+v", o._statusCode, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) String() string {
	return fmt.Sprintf("[GET /services/haproxy/runtime/acl_file_entries][%d] GetServicesHaproxyRuntimeACLFileEntries default  %+v", o._statusCode, o.Payload)
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetServicesHaproxyRuntimeACLFileEntriesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
