// Code generated by go-swagger; DO NOT EDIT.

package http_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v5/models"
)

// CreateHTTPCheckReader is a Reader for the CreateHTTPCheck structure.
type CreateHTTPCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateHTTPCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateHTTPCheckCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewCreateHTTPCheckAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateHTTPCheckBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateHTTPCheckConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateHTTPCheckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateHTTPCheckCreated creates a CreateHTTPCheckCreated with default headers values
func NewCreateHTTPCheckCreated() *CreateHTTPCheckCreated {
	return &CreateHTTPCheckCreated{}
}

/*
CreateHTTPCheckCreated describes a response with status code 201, with default header values.

HTTP check created
*/
type CreateHTTPCheckCreated struct {
	Payload *models.HTTPCheck
}

// IsSuccess returns true when this create Http check created response has a 2xx status code
func (o *CreateHTTPCheckCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create Http check created response has a 3xx status code
func (o *CreateHTTPCheckCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create Http check created response has a 4xx status code
func (o *CreateHTTPCheckCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create Http check created response has a 5xx status code
func (o *CreateHTTPCheckCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create Http check created response a status code equal to that given
func (o *CreateHTTPCheckCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create Http check created response
func (o *CreateHTTPCheckCreated) Code() int {
	return 201
}

func (o *CreateHTTPCheckCreated) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckCreated  %+v", 201, o.Payload)
}

func (o *CreateHTTPCheckCreated) String() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckCreated  %+v", 201, o.Payload)
}

func (o *CreateHTTPCheckCreated) GetPayload() *models.HTTPCheck {
	return o.Payload
}

func (o *CreateHTTPCheckCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPCheck)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPCheckAccepted creates a CreateHTTPCheckAccepted with default headers values
func NewCreateHTTPCheckAccepted() *CreateHTTPCheckAccepted {
	return &CreateHTTPCheckAccepted{}
}

/*
CreateHTTPCheckAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type CreateHTTPCheckAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string

	Payload *models.HTTPCheck
}

// IsSuccess returns true when this create Http check accepted response has a 2xx status code
func (o *CreateHTTPCheckAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create Http check accepted response has a 3xx status code
func (o *CreateHTTPCheckAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create Http check accepted response has a 4xx status code
func (o *CreateHTTPCheckAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this create Http check accepted response has a 5xx status code
func (o *CreateHTTPCheckAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this create Http check accepted response a status code equal to that given
func (o *CreateHTTPCheckAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the create Http check accepted response
func (o *CreateHTTPCheckAccepted) Code() int {
	return 202
}

func (o *CreateHTTPCheckAccepted) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckAccepted  %+v", 202, o.Payload)
}

func (o *CreateHTTPCheckAccepted) String() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckAccepted  %+v", 202, o.Payload)
}

func (o *CreateHTTPCheckAccepted) GetPayload() *models.HTTPCheck {
	return o.Payload
}

func (o *CreateHTTPCheckAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	o.Payload = new(models.HTTPCheck)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPCheckBadRequest creates a CreateHTTPCheckBadRequest with default headers values
func NewCreateHTTPCheckBadRequest() *CreateHTTPCheckBadRequest {
	return &CreateHTTPCheckBadRequest{}
}

/*
CreateHTTPCheckBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateHTTPCheckBadRequest struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this create Http check bad request response has a 2xx status code
func (o *CreateHTTPCheckBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create Http check bad request response has a 3xx status code
func (o *CreateHTTPCheckBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create Http check bad request response has a 4xx status code
func (o *CreateHTTPCheckBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create Http check bad request response has a 5xx status code
func (o *CreateHTTPCheckBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create Http check bad request response a status code equal to that given
func (o *CreateHTTPCheckBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create Http check bad request response
func (o *CreateHTTPCheckBadRequest) Code() int {
	return 400
}

func (o *CreateHTTPCheckBadRequest) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckBadRequest  %+v", 400, o.Payload)
}

func (o *CreateHTTPCheckBadRequest) String() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckBadRequest  %+v", 400, o.Payload)
}

func (o *CreateHTTPCheckBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateHTTPCheckBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPCheckConflict creates a CreateHTTPCheckConflict with default headers values
func NewCreateHTTPCheckConflict() *CreateHTTPCheckConflict {
	return &CreateHTTPCheckConflict{}
}

/*
CreateHTTPCheckConflict describes a response with status code 409, with default header values.

The specified resource already exists
*/
type CreateHTTPCheckConflict struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this create Http check conflict response has a 2xx status code
func (o *CreateHTTPCheckConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create Http check conflict response has a 3xx status code
func (o *CreateHTTPCheckConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create Http check conflict response has a 4xx status code
func (o *CreateHTTPCheckConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create Http check conflict response has a 5xx status code
func (o *CreateHTTPCheckConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create Http check conflict response a status code equal to that given
func (o *CreateHTTPCheckConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create Http check conflict response
func (o *CreateHTTPCheckConflict) Code() int {
	return 409
}

func (o *CreateHTTPCheckConflict) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckConflict  %+v", 409, o.Payload)
}

func (o *CreateHTTPCheckConflict) String() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHttpCheckConflict  %+v", 409, o.Payload)
}

func (o *CreateHTTPCheckConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateHTTPCheckConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPCheckDefault creates a CreateHTTPCheckDefault with default headers values
func NewCreateHTTPCheckDefault(code int) *CreateHTTPCheckDefault {
	return &CreateHTTPCheckDefault{
		_statusCode: code,
	}
}

/*
CreateHTTPCheckDefault describes a response with status code -1, with default header values.

General Error
*/
type CreateHTTPCheckDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this create HTTP check default response has a 2xx status code
func (o *CreateHTTPCheckDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create HTTP check default response has a 3xx status code
func (o *CreateHTTPCheckDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create HTTP check default response has a 4xx status code
func (o *CreateHTTPCheckDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create HTTP check default response has a 5xx status code
func (o *CreateHTTPCheckDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create HTTP check default response a status code equal to that given
func (o *CreateHTTPCheckDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create HTTP check default response
func (o *CreateHTTPCheckDefault) Code() int {
	return o._statusCode
}

func (o *CreateHTTPCheckDefault) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHTTPCheck default  %+v", o._statusCode, o.Payload)
}

func (o *CreateHTTPCheckDefault) String() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_checks][%d] createHTTPCheck default  %+v", o._statusCode, o.Payload)
}

func (o *CreateHTTPCheckDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateHTTPCheckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
