// Code generated by go-swagger; DO NOT EDIT.

package http_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v4/models"
)

// ReplaceHTTPCheckReader is a Reader for the ReplaceHTTPCheck structure.
type ReplaceHTTPCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceHTTPCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceHTTPCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewReplaceHTTPCheckAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReplaceHTTPCheckBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReplaceHTTPCheckNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewReplaceHTTPCheckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReplaceHTTPCheckOK creates a ReplaceHTTPCheckOK with default headers values
func NewReplaceHTTPCheckOK() *ReplaceHTTPCheckOK {
	return &ReplaceHTTPCheckOK{}
}

/*
ReplaceHTTPCheckOK describes a response with status code 200, with default header values.

HTTP check replaced
*/
type ReplaceHTTPCheckOK struct {
	Payload *models.HTTPCheck
}

// IsSuccess returns true when this replace Http check o k response has a 2xx status code
func (o *ReplaceHTTPCheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this replace Http check o k response has a 3xx status code
func (o *ReplaceHTTPCheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this replace Http check o k response has a 4xx status code
func (o *ReplaceHTTPCheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this replace Http check o k response has a 5xx status code
func (o *ReplaceHTTPCheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this replace Http check o k response a status code equal to that given
func (o *ReplaceHTTPCheckOK) IsCode(code int) bool {
	return code == 200
}

func (o *ReplaceHTTPCheckOK) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckOK  %+v", 200, o.Payload)
}

func (o *ReplaceHTTPCheckOK) String() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckOK  %+v", 200, o.Payload)
}

func (o *ReplaceHTTPCheckOK) GetPayload() *models.HTTPCheck {
	return o.Payload
}

func (o *ReplaceHTTPCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPCheck)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceHTTPCheckAccepted creates a ReplaceHTTPCheckAccepted with default headers values
func NewReplaceHTTPCheckAccepted() *ReplaceHTTPCheckAccepted {
	return &ReplaceHTTPCheckAccepted{}
}

/*
ReplaceHTTPCheckAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type ReplaceHTTPCheckAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string

	Payload *models.HTTPCheck
}

// IsSuccess returns true when this replace Http check accepted response has a 2xx status code
func (o *ReplaceHTTPCheckAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this replace Http check accepted response has a 3xx status code
func (o *ReplaceHTTPCheckAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this replace Http check accepted response has a 4xx status code
func (o *ReplaceHTTPCheckAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this replace Http check accepted response has a 5xx status code
func (o *ReplaceHTTPCheckAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this replace Http check accepted response a status code equal to that given
func (o *ReplaceHTTPCheckAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *ReplaceHTTPCheckAccepted) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckAccepted  %+v", 202, o.Payload)
}

func (o *ReplaceHTTPCheckAccepted) String() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckAccepted  %+v", 202, o.Payload)
}

func (o *ReplaceHTTPCheckAccepted) GetPayload() *models.HTTPCheck {
	return o.Payload
}

func (o *ReplaceHTTPCheckAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	o.Payload = new(models.HTTPCheck)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceHTTPCheckBadRequest creates a ReplaceHTTPCheckBadRequest with default headers values
func NewReplaceHTTPCheckBadRequest() *ReplaceHTTPCheckBadRequest {
	return &ReplaceHTTPCheckBadRequest{}
}

/*
ReplaceHTTPCheckBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ReplaceHTTPCheckBadRequest struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this replace Http check bad request response has a 2xx status code
func (o *ReplaceHTTPCheckBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this replace Http check bad request response has a 3xx status code
func (o *ReplaceHTTPCheckBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this replace Http check bad request response has a 4xx status code
func (o *ReplaceHTTPCheckBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this replace Http check bad request response has a 5xx status code
func (o *ReplaceHTTPCheckBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this replace Http check bad request response a status code equal to that given
func (o *ReplaceHTTPCheckBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ReplaceHTTPCheckBadRequest) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckBadRequest  %+v", 400, o.Payload)
}

func (o *ReplaceHTTPCheckBadRequest) String() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckBadRequest  %+v", 400, o.Payload)
}

func (o *ReplaceHTTPCheckBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceHTTPCheckBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceHTTPCheckNotFound creates a ReplaceHTTPCheckNotFound with default headers values
func NewReplaceHTTPCheckNotFound() *ReplaceHTTPCheckNotFound {
	return &ReplaceHTTPCheckNotFound{}
}

/*
ReplaceHTTPCheckNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type ReplaceHTTPCheckNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this replace Http check not found response has a 2xx status code
func (o *ReplaceHTTPCheckNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this replace Http check not found response has a 3xx status code
func (o *ReplaceHTTPCheckNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this replace Http check not found response has a 4xx status code
func (o *ReplaceHTTPCheckNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this replace Http check not found response has a 5xx status code
func (o *ReplaceHTTPCheckNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this replace Http check not found response a status code equal to that given
func (o *ReplaceHTTPCheckNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ReplaceHTTPCheckNotFound) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckNotFound  %+v", 404, o.Payload)
}

func (o *ReplaceHTTPCheckNotFound) String() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHttpCheckNotFound  %+v", 404, o.Payload)
}

func (o *ReplaceHTTPCheckNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceHTTPCheckNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceHTTPCheckDefault creates a ReplaceHTTPCheckDefault with default headers values
func NewReplaceHTTPCheckDefault(code int) *ReplaceHTTPCheckDefault {
	return &ReplaceHTTPCheckDefault{
		_statusCode: code,
	}
}

/*
ReplaceHTTPCheckDefault describes a response with status code -1, with default header values.

General Error
*/
type ReplaceHTTPCheckDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the replace HTTP check default response
func (o *ReplaceHTTPCheckDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this replace HTTP check default response has a 2xx status code
func (o *ReplaceHTTPCheckDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this replace HTTP check default response has a 3xx status code
func (o *ReplaceHTTPCheckDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this replace HTTP check default response has a 4xx status code
func (o *ReplaceHTTPCheckDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this replace HTTP check default response has a 5xx status code
func (o *ReplaceHTTPCheckDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this replace HTTP check default response a status code equal to that given
func (o *ReplaceHTTPCheckDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ReplaceHTTPCheckDefault) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHTTPCheck default  %+v", o._statusCode, o.Payload)
}

func (o *ReplaceHTTPCheckDefault) String() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/http_checks/{index}][%d] replaceHTTPCheck default  %+v", o._statusCode, o.Payload)
}

func (o *ReplaceHTTPCheckDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceHTTPCheckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
