// Code generated by go-swagger; DO NOT EDIT.

package spoe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v5/models"
)

// DeleteSpoeFileReader is a Reader for the DeleteSpoeFile structure.
type DeleteSpoeFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSpoeFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSpoeFileNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteSpoeFileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteSpoeFileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSpoeFileNoContent creates a DeleteSpoeFileNoContent with default headers values
func NewDeleteSpoeFileNoContent() *DeleteSpoeFileNoContent {
	return &DeleteSpoeFileNoContent{}
}

/*
DeleteSpoeFileNoContent describes a response with status code 204, with default header values.

SPOE file deleted
*/
type DeleteSpoeFileNoContent struct {
}

// IsSuccess returns true when this delete spoe file no content response has a 2xx status code
func (o *DeleteSpoeFileNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete spoe file no content response has a 3xx status code
func (o *DeleteSpoeFileNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete spoe file no content response has a 4xx status code
func (o *DeleteSpoeFileNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete spoe file no content response has a 5xx status code
func (o *DeleteSpoeFileNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete spoe file no content response a status code equal to that given
func (o *DeleteSpoeFileNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete spoe file no content response
func (o *DeleteSpoeFileNoContent) Code() int {
	return 204
}

func (o *DeleteSpoeFileNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/spoe/spoe_files/{name}][%d] deleteSpoeFileNoContent ", 204)
}

func (o *DeleteSpoeFileNoContent) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/spoe/spoe_files/{name}][%d] deleteSpoeFileNoContent ", 204)
}

func (o *DeleteSpoeFileNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSpoeFileNotFound creates a DeleteSpoeFileNotFound with default headers values
func NewDeleteSpoeFileNotFound() *DeleteSpoeFileNotFound {
	return &DeleteSpoeFileNotFound{}
}

/*
DeleteSpoeFileNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type DeleteSpoeFileNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this delete spoe file not found response has a 2xx status code
func (o *DeleteSpoeFileNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete spoe file not found response has a 3xx status code
func (o *DeleteSpoeFileNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete spoe file not found response has a 4xx status code
func (o *DeleteSpoeFileNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete spoe file not found response has a 5xx status code
func (o *DeleteSpoeFileNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete spoe file not found response a status code equal to that given
func (o *DeleteSpoeFileNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete spoe file not found response
func (o *DeleteSpoeFileNotFound) Code() int {
	return 404
}

func (o *DeleteSpoeFileNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/spoe/spoe_files/{name}][%d] deleteSpoeFileNotFound  %+v", 404, o.Payload)
}

func (o *DeleteSpoeFileNotFound) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/spoe/spoe_files/{name}][%d] deleteSpoeFileNotFound  %+v", 404, o.Payload)
}

func (o *DeleteSpoeFileNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSpoeFileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSpoeFileDefault creates a DeleteSpoeFileDefault with default headers values
func NewDeleteSpoeFileDefault(code int) *DeleteSpoeFileDefault {
	return &DeleteSpoeFileDefault{
		_statusCode: code,
	}
}

/*
DeleteSpoeFileDefault describes a response with status code -1, with default header values.

General Error
*/
type DeleteSpoeFileDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this delete spoe file default response has a 2xx status code
func (o *DeleteSpoeFileDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete spoe file default response has a 3xx status code
func (o *DeleteSpoeFileDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete spoe file default response has a 4xx status code
func (o *DeleteSpoeFileDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete spoe file default response has a 5xx status code
func (o *DeleteSpoeFileDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete spoe file default response a status code equal to that given
func (o *DeleteSpoeFileDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete spoe file default response
func (o *DeleteSpoeFileDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSpoeFileDefault) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/spoe/spoe_files/{name}][%d] deleteSpoeFile default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSpoeFileDefault) String() string {
	return fmt.Sprintf("[DELETE /services/haproxy/spoe/spoe_files/{name}][%d] deleteSpoeFile default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSpoeFileDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSpoeFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
