// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v5/models"
)

// GetOneStorageSSLCertificateReader is a Reader for the GetOneStorageSSLCertificate structure.
type GetOneStorageSSLCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOneStorageSSLCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOneStorageSSLCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetOneStorageSSLCertificateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetOneStorageSSLCertificateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetOneStorageSSLCertificateOK creates a GetOneStorageSSLCertificateOK with default headers values
func NewGetOneStorageSSLCertificateOK() *GetOneStorageSSLCertificateOK {
	return &GetOneStorageSSLCertificateOK{}
}

/*
GetOneStorageSSLCertificateOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetOneStorageSSLCertificateOK struct {
	Payload *models.SslCertificate
}

// IsSuccess returns true when this get one storage s s l certificate o k response has a 2xx status code
func (o *GetOneStorageSSLCertificateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get one storage s s l certificate o k response has a 3xx status code
func (o *GetOneStorageSSLCertificateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get one storage s s l certificate o k response has a 4xx status code
func (o *GetOneStorageSSLCertificateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get one storage s s l certificate o k response has a 5xx status code
func (o *GetOneStorageSSLCertificateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get one storage s s l certificate o k response a status code equal to that given
func (o *GetOneStorageSSLCertificateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get one storage s s l certificate o k response
func (o *GetOneStorageSSLCertificateOK) Code() int {
	return 200
}

func (o *GetOneStorageSSLCertificateOK) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/storage/ssl_certificates/{name}][%d] getOneStorageSSLCertificateOK  %+v", 200, o.Payload)
}

func (o *GetOneStorageSSLCertificateOK) String() string {
	return fmt.Sprintf("[GET /services/haproxy/storage/ssl_certificates/{name}][%d] getOneStorageSSLCertificateOK  %+v", 200, o.Payload)
}

func (o *GetOneStorageSSLCertificateOK) GetPayload() *models.SslCertificate {
	return o.Payload
}

func (o *GetOneStorageSSLCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SslCertificate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOneStorageSSLCertificateNotFound creates a GetOneStorageSSLCertificateNotFound with default headers values
func NewGetOneStorageSSLCertificateNotFound() *GetOneStorageSSLCertificateNotFound {
	return &GetOneStorageSSLCertificateNotFound{}
}

/*
GetOneStorageSSLCertificateNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type GetOneStorageSSLCertificateNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get one storage s s l certificate not found response has a 2xx status code
func (o *GetOneStorageSSLCertificateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get one storage s s l certificate not found response has a 3xx status code
func (o *GetOneStorageSSLCertificateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get one storage s s l certificate not found response has a 4xx status code
func (o *GetOneStorageSSLCertificateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get one storage s s l certificate not found response has a 5xx status code
func (o *GetOneStorageSSLCertificateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get one storage s s l certificate not found response a status code equal to that given
func (o *GetOneStorageSSLCertificateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get one storage s s l certificate not found response
func (o *GetOneStorageSSLCertificateNotFound) Code() int {
	return 404
}

func (o *GetOneStorageSSLCertificateNotFound) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/storage/ssl_certificates/{name}][%d] getOneStorageSSLCertificateNotFound  %+v", 404, o.Payload)
}

func (o *GetOneStorageSSLCertificateNotFound) String() string {
	return fmt.Sprintf("[GET /services/haproxy/storage/ssl_certificates/{name}][%d] getOneStorageSSLCertificateNotFound  %+v", 404, o.Payload)
}

func (o *GetOneStorageSSLCertificateNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOneStorageSSLCertificateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOneStorageSSLCertificateDefault creates a GetOneStorageSSLCertificateDefault with default headers values
func NewGetOneStorageSSLCertificateDefault(code int) *GetOneStorageSSLCertificateDefault {
	return &GetOneStorageSSLCertificateDefault{
		_statusCode: code,
	}
}

/*
GetOneStorageSSLCertificateDefault describes a response with status code -1, with default header values.

General Error
*/
type GetOneStorageSSLCertificateDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get one storage s s l certificate default response has a 2xx status code
func (o *GetOneStorageSSLCertificateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get one storage s s l certificate default response has a 3xx status code
func (o *GetOneStorageSSLCertificateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get one storage s s l certificate default response has a 4xx status code
func (o *GetOneStorageSSLCertificateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get one storage s s l certificate default response has a 5xx status code
func (o *GetOneStorageSSLCertificateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get one storage s s l certificate default response a status code equal to that given
func (o *GetOneStorageSSLCertificateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get one storage s s l certificate default response
func (o *GetOneStorageSSLCertificateDefault) Code() int {
	return o._statusCode
}

func (o *GetOneStorageSSLCertificateDefault) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/storage/ssl_certificates/{name}][%d] getOneStorageSSLCertificate default  %+v", o._statusCode, o.Payload)
}

func (o *GetOneStorageSSLCertificateDefault) String() string {
	return fmt.Sprintf("[GET /services/haproxy/storage/ssl_certificates/{name}][%d] getOneStorageSSLCertificate default  %+v", o._statusCode, o.Payload)
}

func (o *GetOneStorageSSLCertificateDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOneStorageSSLCertificateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
