// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v5/models"
)

// GetHealthReader is a Reader for the GetHealth structure.
type GetHealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetHealthDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetHealthOK creates a GetHealthOK with default headers values
func NewGetHealthOK() *GetHealthOK {
	return &GetHealthOK{}
}

/*
GetHealthOK describes a response with status code 200, with default header values.

Success
*/
type GetHealthOK struct {
	Payload *models.Health
}

// IsSuccess returns true when this get health o k response has a 2xx status code
func (o *GetHealthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get health o k response has a 3xx status code
func (o *GetHealthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get health o k response has a 4xx status code
func (o *GetHealthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get health o k response has a 5xx status code
func (o *GetHealthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get health o k response a status code equal to that given
func (o *GetHealthOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get health o k response
func (o *GetHealthOK) Code() int {
	return 200
}

func (o *GetHealthOK) Error() string {
	return fmt.Sprintf("[GET /health][%d] getHealthOK  %+v", 200, o.Payload)
}

func (o *GetHealthOK) String() string {
	return fmt.Sprintf("[GET /health][%d] getHealthOK  %+v", 200, o.Payload)
}

func (o *GetHealthOK) GetPayload() *models.Health {
	return o.Payload
}

func (o *GetHealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Health)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHealthDefault creates a GetHealthDefault with default headers values
func NewGetHealthDefault(code int) *GetHealthDefault {
	return &GetHealthDefault{
		_statusCode: code,
	}
}

/*
GetHealthDefault describes a response with status code -1, with default header values.

General Error
*/
type GetHealthDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// IsSuccess returns true when this get health default response has a 2xx status code
func (o *GetHealthDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get health default response has a 3xx status code
func (o *GetHealthDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get health default response has a 4xx status code
func (o *GetHealthDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get health default response has a 5xx status code
func (o *GetHealthDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get health default response a status code equal to that given
func (o *GetHealthDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get health default response
func (o *GetHealthDefault) Code() int {
	return o._statusCode
}

func (o *GetHealthDefault) Error() string {
	return fmt.Sprintf("[GET /health][%d] getHealth default  %+v", o._statusCode, o.Payload)
}

func (o *GetHealthDefault) String() string {
	return fmt.Sprintf("[GET /health][%d] getHealth default  %+v", o._statusCode, o.Payload)
}

func (o *GetHealthDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetHealthDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
